site_name: Стандарты разработки 1С от Ингвара
site_url: https://v8std.ru
site_author: Ingvar Vilkman
site_description: >-
  Частный взгляд Ингвара.

repo_name: zeegin/v8std
repo_url: https://github.com/zeegin/v8std
edit_uri: edit/master/docs

copyright: No Rights Reserved <a href="https://creativecommons.org/publicdomain/zero/1.0/deed.ru">CREATIVE COMMONS CC0</a>

theme:
  name: material
  custom_dir: overrides

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  language: ru
  logo: 'assets/images/logo.png'
  favicon: 'assets/images/logo.png'

  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - navigation.indexes
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Автоматически

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Выключить свет

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Включить свет
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo

plugins:
  - search:
      lang:
        - ru

extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/zeegin/v8std'
    - icon: fontawesome/brands/telegram
      link: 'https://t.me/v8std'
  consent:
    title: Cookie
    description: >- 
      Мы используем файлы cookie для распознавания ваших повторных посещений и предпочтений,
      а также для оценки эффективности нашей документации и того, находят ли пользователи то, что ищут.
      С вашего согласия вы помогаете нам сделать нашу документацию лучше.
    cookies:
      analytics: Yandex.Metrika


extra_css:
  - 'assets/stylesheets/extra.css'

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: zeegin
      repo: v8std
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

# Page tree
nav:
  - Домашняя: index.md
  - Стандарты:
    - ИТС:
      - Создание и изменение объектов метаданных:
        - Организация работы конфигурации:
          - Общие требования к конфигурации: std/467.md
          - Работа в разных часовых поясах: std/643.md
      - Реализация обработки данных:
        - Работа с запросами:
          - Проверка на пустой результат выполнения запроса: std/438.md
          - Особенности использования в запросах оператора ПОДОБНО: std/726.md
        - Оптимизация запросов:
          - Дополнительные индексы: std/791.md
        - Обработка и модификация данных:
          - "Транзакции: правила использования": std/783.md
      - Соглашения при написании кода:
        - Оформление модулей:
          - Тексты модулей: std/456.md
          - Структура модуля: std/455.md
          - Правила образования имен переменных: std/454.md
          - Имена процедур и функций: std/647.md
        - Использование конструкций встроенного языка:
          - Ограничение на использование оператора Перейти: std/547.md
      - Общие вопросы безопасности: 
        - Безопасность прикладного программного интерфейса сервера: std/678.md
  - Помочь: support.md
